application: travelmapster
version: 1
runtime: python
api_version: 1

handlers:
- url: /cron
  script: scripts/main.py
  
- url: /
  static_files: web/index.html
  upload: web/index.html

- url: /
  static_dir: web
  
- url: /maps
  script: maps/updateTables.py