application: mapstertravel
version: 1
runtime: python
api_version: 1

handlers:
- url: /cron1
  script: scripts/main1.py  

- url: /cron2
  script: scripts/main2.py  
  
- url: /cron3
  script: scripts/main3.py  
  
- url: /cron4
  script: scripts/main4.py  
  
- url: /cron5
  script: scripts/main5.py 
  
- url: /cron6
  script: scripts/main6.py  

- url: /cron7
  script: scripts/main7.py  
  
- url: /cron8
  script: scripts/main8.py  
  
- url: /cron9
  script: scripts/main9.py  
  
- url: /cron10
  script: scripts/main10.py 
  
- url: /static
  static_dir: static
  
- url: /images
  static_dir: images
  
- url: /.*
  script: scripts/mainpage.py